databases:
  - name: chatroom_thoriqas
    databaseName: chatroom_thoriqas
    user: user_thoriqas
    plan: free

services:
  - type: web
    name: chatroom_thoriqas
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chatroom_thoriqas
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
